### ISSUE TITLE
Version 2.2.0 did not import components

### ISSUE THREAD

**Issue by rafaelkowal** [robertlevonyan/media-picker#25]
I am using the kotlin version when updating to the new version 2.2.0, it is not importing the pickerDialog class, ![Captura de Tela 2022-04-04 às 14 34 35](https://user-images.githubusercontent.com/445756/161601731-771dde0d-6446-49f8-b0ba-a8bf12343b6f.png)

it seems that it imports the compose folder.
![Captura de Tela 2022-04-04 às 14 44 34](https://user-images.githubusercontent.com/445756/161601875-528c4766-e678-4ec8-8a79-4aec36e6950c.png)

**Comment by robertlevonyan** [comment]
Sorry, I did a mistake during publishing ( You can check now the version `2.2.1`

**Comment by rafaelkowal** [comment]
Robert, for me it still has the compose

![Captura de Tela 2022-04-05 às 08 07 01](https://user-images.githubusercontent.com/445756/161740987-80583f7c-a3fd-4c59-ac88-acd964184f66.png)

**Comment by robertlevonyan** [comment]
now it's fixed in 2.2.2, now for sure )
